import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

// Guards the contract between the frontend and Tauri's capability ACL, after
// the defect class that shipped and stayed hidden: main.tsx reveals the window
// with getCurrentWindow().show(), capabilities/default.json never granted
// core:window:allow-show, Tauri rejected the call at runtime, and the
// three-second fallback thread in lib.rs showed the window instead. The only
// symptom was that every launch waited those three seconds. It went unnoticed
// from 2026-09-21 until the reveal was instrumented.
//
// The import compiles whether or not the capability permits the command, so the
// check reads what the source actually calls. Nothing here reads
// src-tauri/gen/schemas: that is generated by a Rust build, and the job running
// this test never compiles Rust, so a guard depending on it would pass on a
// developer's machine and fail on a clean checkout.

const ROOT = join(import.meta.dirname, "..", "..");
const CAPABILITY = join(ROOT, "src-tauri", "capabilities", "default.json");
const FRONTEND = join(ROOT, "src");

/** `getCurrentWindow().method(` on one line, called directly on the literal. */
const DIRECT_CALL = /getCurrentWindow\(\)\s*\.\s*([A-Za-z]+)\s*\(/g;

function sourceFilesUnder(dir: string): string[] {
  const found: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      found.push(...sourceFilesUnder(path));
    } else if (/\.tsx?$/.test(entry.name) && !/\.test\.tsx?$/.test(entry.name)) {
      found.push(path);
    }
  }
  return found;
}

/**
 * The permission a window method needs. The JS method is camelCase and the
 * command it invokes is snake_case, from which the permission identifier is
 * built: `show` -> `show` -> allow-show, `isVisible` -> `is_visible` ->
 * allow-is-visible.
 */
function permissionFor(method: string): string {
  const command = method.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`);
  return `core:window:allow-${command.replace(/_/g, "-")}`;
}

function scanFrontend() {
  const calls = new Map<string, string[]>();
  let mentions = 0;
  let matched = 0;
  for (const file of sourceFilesUnder(FRONTEND)) {
    const where = file.slice(ROOT.length + 1);
    // Import statements name the function without calling it.
    const source = readFileSync(file, "utf8").replace(/import[\s\S]*?;/g, "");
    mentions += (source.match(/getCurrentWindow/g) ?? []).length;
    for (const match of source.matchAll(DIRECT_CALL)) {
      matched += 1;
      calls.set(match[1], [...(calls.get(match[1]) ?? []), where]);
    }
  }
  return { calls, mentions, matched };
}

test("the capability grants a permission for every window method the frontend calls", () => {
  const capability = JSON.parse(readFileSync(CAPABILITY, "utf8")) as { permissions: string[] };
  const granted = new Set(capability.permissions);
  const { calls, mentions, matched } = scanFrontend();

  // A scan that finds nothing is a stale scan, not a passing one: the reveal in
  // main.tsx is the reason this file exists.
  assert.ok(
    calls.size > 0,
    `no getCurrentWindow() call found under ${FRONTEND}; this scan no longer matches the source`,
  );

  // The scan only understands a call made directly on the literal. The moment
  // someone keeps the window in a variable, this guard would stop seeing the
  // calls it is here to check and pass while checking nothing. Fail loudly
  // instead of going quiet. Imports are stripped first, so a difference here is
  // a receiver kept in a variable, an optional chain, or a break inside the call.
  assert.equal(
    mentions,
    matched,
    `${mentions - matched} occurrence(s) of getCurrentWindow() are not the direct ` +
      `getCurrentWindow().method() form this scan understands. Call the method on the ` +
      `literal, or extend the scan, so the guard keeps seeing every call.`,
  );

  for (const [method, where] of calls) {
    const permission = permissionFor(method);
    assert.ok(
      granted.has(permission),
      `${where.join(", ")} calls getCurrentWindow().${method}(), and ` +
        `src-tauri/capabilities/default.json does not grant ${permission}. ` +
        `Grant it there. If ${method} is not an ACL-gated command (the event ` +
        `helpers, such as onFocusChanged, are not), extend this test rather than ` +
        `granting a permission that does not exist: tauri-build rejects an ` +
        `unknown identifier, and the error it prints does not point back here.`,
    );
  }
});
