use std::fs;
use std::io::Write;
use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::error::AppResult;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Cookie {
    pub domain: String,
    pub include_subdomains: bool,
    pub path: String,
    pub secure: bool,
    pub expiration: u64,
    pub name: String,
    pub value: String,
}

pub fn parse_netscape_cookies(text: &str) -> AppResult<Vec<Cookie>> {
    let mut cookies = Vec::new();

    for line in text.lines() {
        let line = line.trim_end();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        let parts: Vec<&str> = line.split('\t').collect();
        if parts.len() < 7 {
            continue;
        }

        let include_subdomains = parts[1].eq_ignore_ascii_case("TRUE");
        let secure = parts[3].eq_ignore_ascii_case("TRUE");
        let expiration = parts[4].parse::<u64>().unwrap_or(0);

        cookies.push(Cookie {
            domain: parts[0].to_string(),
            include_subdomains,
            path: parts[2].to_string(),
            secure,
            expiration,
            name: parts[5].to_string(),
            value: parts[6].to_string(),
        });
    }

    Ok(cookies)
}

pub fn has_bilibili_sessdata(cookies: &[Cookie]) -> bool {
    cookies
        .iter()
        .any(|cookie| cookie.name == "SESSDATA" && !cookie.value.is_empty())
}

/// Ensure SESSDATA cookies have a Bilibili domain so Netscape export / yt-dlp work.
pub fn normalize_bilibili_cookies(cookies: &[Cookie]) -> Vec<Cookie> {
    cookies
        .iter()
        .map(|cookie| {
            let mut c = cookie.clone();
            if c.name == "SESSDATA" && (c.domain.is_empty() || !c.domain.contains("bilibili.com")) {
                c.domain = ".bilibili.com".into();
                c.include_subdomains = true;
            }
            if c.path.is_empty() {
                c.path = "/".into();
            }
            c
        })
        .collect()
}

pub fn write_netscape_file(path: &Path, cookies: &[Cookie]) -> AppResult<()> {
    let mut file = fs::File::create(path)?;
    writeln!(file, "# Netscape HTTP Cookie File")?;
    writeln!(file, "# https://curl.haxx.se/docs/http-cookies.html")?;
    writeln!(
        file,
        "# This file was generated by VideoFetch. Edit at your own risk."
    )?;

    for cookie in cookies {
        writeln!(
            file,
            "{}\t{}\t{}\t{}\t{}\t{}\t{}",
            cookie.domain,
            if cookie.include_subdomains {
                "TRUE"
            } else {
                "FALSE"
            },
            cookie.path,
            if cookie.secure { "TRUE" } else { "FALSE" },
            cookie.expiration,
            cookie.name,
            cookie.value,
        )?;
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = r#"# Netscape HTTP Cookie File
.bilibili.com	TRUE	/	FALSE	0	SESSDATA	abc123
.bilibili.com	TRUE	/	FALSE	0	bili_jct	tok
"#;

    #[test]
    fn parses_sessdata() {
        let cookies = parse_netscape_cookies(SAMPLE).unwrap();
        assert!(has_bilibili_sessdata(&cookies));
        assert_eq!(
            cookies.iter().find(|c| c.name == "SESSDATA").unwrap().value,
            "abc123"
        );
    }

    #[test]
    fn rejects_garbage() {
        assert!(
            parse_netscape_cookies("not a cookies file")
                .unwrap()
                .is_empty()
        );
    }
}
