use std::fs;
use std::io::Write;
use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::error::AppResult;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Cookie {
    pub domain: String,
    pub include_subdomains: bool,
    pub path: String,
    pub secure: bool,
    pub expiration: u64,
    pub name: String,
    pub value: String,
}

pub fn parse_netscape_cookies(text: &str) -> AppResult<Vec<Cookie>> {
    let mut cookies = Vec::new();

    for line in text.lines() {
        let line = line.trim_end();
        // Browser extensions mark HttpOnly cookies with a `#HttpOnly_` prefix
        // so other Netscape readers skip them; yt-dlp strips it back off.
        // Bilibili's SESSDATA is HttpOnly, so reading the line as a comment
        // dropped exactly the cookie this import exists to capture.
        let line = line.strip_prefix("#HttpOnly_").unwrap_or(line);
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        let parts: Vec<&str> = line.split('\t').collect();
        if parts.len() < 7 {
            continue;
        }

        let include_subdomains = parts[1].eq_ignore_ascii_case("TRUE");
        let secure = parts[3].eq_ignore_ascii_case("TRUE");
        let expiration = parts[4].parse::<u64>().unwrap_or(0);

        cookies.push(Cookie {
            domain: parts[0].to_string(),
            include_subdomains,
            path: parts[2].to_string(),
            secure,
            expiration,
            name: parts[5].to_string(),
            value: parts[6].to_string(),
        });
    }

    Ok(cookies)
}

pub fn has_bilibili_sessdata(cookies: &[Cookie]) -> bool {
    cookies
        .iter()
        .any(|cookie| cookie.name == "SESSDATA" && !cookie.value.is_empty())
}

/// True for Bilibili-owned domains (`bilibili.com` or any subdomain), guarding
/// against suffix lookalikes like `bilibili.com.evil.com`.
pub fn is_bilibili_domain(domain: &str) -> bool {
    let d = domain.trim_start_matches('.').to_ascii_lowercase();
    d == "bilibili.com" || d.ends_with(".bilibili.com")
}

/// Ensure SESSDATA cookies have a Bilibili domain so Netscape export / yt-dlp work,
/// and drop cookies from other domains (captcha/tracking cookies the login WebView
/// accumulates are not needed for downloads and must not be persisted). Only a
/// domain-less SESSDATA is rewritten onto `.bilibili.com`; a SESSDATA carrying an
/// explicit foreign domain (including suffix lookalikes) is dropped rather than
/// trusted and re-hosted under the Bilibili domain.
pub fn normalize_bilibili_cookies(cookies: &[Cookie]) -> Vec<Cookie> {
    cookies
        .iter()
        .map(|cookie| {
            let mut c = cookie.clone();
            if c.name == "SESSDATA" && c.domain.is_empty() {
                c.domain = ".bilibili.com".into();
                c.include_subdomains = true;
            }
            if c.path.is_empty() {
                c.path = "/".into();
            }
            c
        })
        .filter(|c| is_bilibili_domain(&c.domain))
        .collect()
}

/// Join stored cookies into a `name=value; name=value` request header, keeping
/// only Bilibili domains and skipping cookies that have already expired.
pub fn cookie_header_for_bilibili(cookies: &[Cookie]) -> String {
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    cookies
        .iter()
        .filter(|c| is_bilibili_domain(&c.domain) && !c.name.is_empty())
        .filter(|c| c.expiration == 0 || c.expiration >= now)
        .map(|c| format!("{}={}", c.name, c.value))
        .collect::<Vec<_>>()
        .join("; ")
}

/// Create the cookie jar owner-only from the moment it exists.
///
/// `File::create` would leave it at `0666 & ~umask` until a later chmod, and
/// a local user who opens the file inside that window keeps the handle — the
/// chmod cannot take back a read that already started. The kernel applies
/// `mode` when it creates the file, so there is no window to lose. A path
/// that already exists keeps its own mode, which is what the caller's fixup
/// covers.
fn create_private_jar(path: &Path) -> std::io::Result<fs::File> {
    let mut opts = fs::OpenOptions::new();
    opts.write(true).create(true).truncate(true);
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        opts.mode(0o600);
    }
    opts.open(path)
}

pub fn write_netscape_file(path: &Path, cookies: &[Cookie]) -> AppResult<()> {
    let mut file = create_private_jar(path)?;
    writeln!(file, "# Netscape HTTP Cookie File")?;
    writeln!(file, "# https://curl.haxx.se/docs/http-cookies.html")?;
    writeln!(
        file,
        "# This file was generated by Video Fetch. Edit at your own risk."
    )?;

    for cookie in cookies {
        writeln!(
            file,
            "{}\t{}\t{}\t{}\t{}\t{}\t{}",
            cookie.domain,
            if cookie.include_subdomains {
                "TRUE"
            } else {
                "FALSE"
            },
            cookie.path,
            if cookie.secure { "TRUE" } else { "FALSE" },
            cookie.expiration,
            cookie.name,
            cookie.value,
        )?;
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = r#"# Netscape HTTP Cookie File
.bilibili.com	TRUE	/	FALSE	0	SESSDATA	abc123
.bilibili.com	TRUE	/	FALSE	0	bili_jct	tok
"#;

    /// Browser extensions mark HttpOnly cookies with a `#HttpOnly_` prefix so
    /// other Netscape readers skip them; yt-dlp strips it. Bilibili's SESSDATA
    /// is HttpOnly, so reading the line as a comment dropped exactly the
    /// cookie the import exists to capture.
    #[test]
    fn parses_httponly_prefixed_lines() {
        let text = "# Netscape HTTP Cookie File\n\
                    #HttpOnly_.bilibili.com\tTRUE\t/\tTRUE\t0\tSESSDATA\tabc123\n";
        let cookies = parse_netscape_cookies(text).unwrap();
        assert_eq!(cookies.len(), 1);
        assert_eq!(cookies[0].name, "SESSDATA");
        assert_eq!(cookies[0].domain, ".bilibili.com");
        assert!(cookies[0].secure);
        assert!(has_bilibili_sessdata(&cookies));
    }

    #[test]
    fn still_skips_comments_and_blank_lines() {
        let text = "# a comment\n\
                    \n\
                    #HttpOnly_.bilibili.com\tTRUE\t/\tTRUE\t0\tSESSDATA\tv\n\
                    #HttpOnly_\n\
                    # trailing comment\n";
        let cookies = parse_netscape_cookies(text).unwrap();
        assert_eq!(cookies.len(), 1);
        assert_eq!(cookies[0].value, "v");
    }

    #[test]
    fn parses_sessdata() {
        let cookies = parse_netscape_cookies(SAMPLE).unwrap();
        assert!(has_bilibili_sessdata(&cookies));
        assert_eq!(
            cookies.iter().find(|c| c.name == "SESSDATA").unwrap().value,
            "abc123"
        );
    }

    #[test]
    fn rejects_garbage() {
        assert!(
            parse_netscape_cookies("not a cookies file")
                .unwrap()
                .is_empty()
        );
    }

    fn cookie(domain: &str, name: &str, value: &str) -> Cookie {
        Cookie {
            domain: domain.into(),
            include_subdomains: domain.starts_with('.'),
            path: "/".into(),
            secure: true,
            expiration: 0,
            name: name.into(),
            value: value.into(),
        }
    }

    /// The jar carries SESSDATA. `File::create` left it at 0666 & ~umask
    /// until auth.rs chmod-ed it afterwards, and a local user who opened the
    /// file inside that window kept the handle — the chmod cannot take back a
    /// read that already started. Asking the kernel for the mode at creation
    /// leaves no window to lose.
    #[cfg(unix)]
    #[test]
    fn write_netscape_file_creates_the_jar_owner_only() {
        use std::os::unix::fs::PermissionsExt;
        let dir = tempfile::tempdir().unwrap();
        let mode_of = |p: &Path| fs::metadata(p).unwrap().permissions().mode() & 0o777;

        // Premise: under a umask of 077 a plain create is 0600 too, and the
        // assertion below could hold without the mode ever being requested.
        let control = dir.path().join("control");
        fs::write(&control, b"x").unwrap();
        assert_ne!(
            mode_of(&control),
            0o600,
            "this umask makes the test vacuous; it cannot tell whether the \
             mode was requested"
        );

        let path = dir.path().join("cookies.txt");
        write_netscape_file(&path, &[cookie(".bilibili.com", "SESSDATA", "secret")]).unwrap();

        assert_eq!(mode_of(&path), 0o600);
    }

    #[test]
    fn normalize_keeps_only_bilibili_domains() {
        let cookies = vec![
            cookie(".bilibili.com", "SESSDATA", "abc"),
            cookie(".bilibili.com", "bili_jct", "tok"),
            cookie(".geetest.com", "gt", "x"),
            cookie(".doubleclick.net", "id", "y"),
        ];
        let normalized = normalize_bilibili_cookies(&cookies);
        let names: Vec<&str> = normalized.iter().map(|c| c.name.as_str()).collect();
        assert_eq!(names, vec!["SESSDATA", "bili_jct"]);
    }

    #[test]
    fn normalize_rewrites_domainless_sessdata() {
        let cookies = vec![cookie("", "SESSDATA", "abc")];
        let normalized = normalize_bilibili_cookies(&cookies);
        assert_eq!(normalized.len(), 1);
        assert_eq!(normalized[0].domain, ".bilibili.com");
        assert!(normalized[0].include_subdomains);
    }

    #[test]
    fn normalize_drops_sessdata_from_foreign_domain() {
        let cookies = vec![cookie(".example.com", "SESSDATA", "abc")];
        let normalized = normalize_bilibili_cookies(&cookies);
        assert!(normalized.is_empty());
    }

    #[test]
    fn normalize_drops_lookalike_domains() {
        let cookies = vec![
            cookie("bilibili.com.evil.com", "SESSDATA", "abc"),
            cookie("bilibili.com.evil.com", "buvid3", "xyz"),
        ];
        let normalized = normalize_bilibili_cookies(&cookies);
        assert!(normalized.is_empty());
    }

    #[test]
    fn cookie_header_keeps_only_bilibili_domains() {
        let cookies = vec![
            cookie(".bilibili.com", "SESSDATA", "abc"),
            cookie(".bilibili.com", "bili_jct", "tok"),
            cookie(".doubleclick.net", "id", "x"),
        ];
        assert_eq!(
            cookie_header_for_bilibili(&cookies),
            "SESSDATA=abc; bili_jct=tok"
        );
    }

    #[test]
    fn cookie_header_skips_expired_cookies() {
        let past = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs() - 60)
            .unwrap_or(0);
        let mut expired = cookie(".bilibili.com", "SESSDATA", "old");
        expired.expiration = past;
        let cookies = vec![expired, cookie(".bilibili.com", "buvid3", "x")];
        assert_eq!(cookie_header_for_bilibili(&cookies), "buvid3=x");
    }

    #[test]
    fn bilibili_domain_matching() {
        assert!(is_bilibili_domain("bilibili.com"));
        assert!(is_bilibili_domain(".bilibili.com"));
        assert!(is_bilibili_domain("www.bilibili.com"));
        assert!(is_bilibili_domain("passport.bilibili.com"));
        assert!(!is_bilibili_domain("bilibili.com.evil.com"));
        assert!(!is_bilibili_domain("notbilibili.com"));
        assert!(!is_bilibili_domain(""));
    }
}
