use std::fs;
use std::io::Write;
use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::error::AppResult;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Cookie {
    pub domain: String,
    pub include_subdomains: bool,
    pub path: String,
    pub secure: bool,
    pub expiration: u64,
    pub name: String,
    pub value: String,
}

pub fn parse_netscape_cookies(text: &str) -> AppResult<Vec<Cookie>> {
    let mut cookies = Vec::new();

    for line in text.lines() {
        let line = line.trim_end();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        let parts: Vec<&str> = line.split('\t').collect();
        if parts.len() < 7 {
            continue;
        }

        let include_subdomains = parts[1].eq_ignore_ascii_case("TRUE");
        let secure = parts[3].eq_ignore_ascii_case("TRUE");
        let expiration = parts[4].parse::<u64>().unwrap_or(0);

        cookies.push(Cookie {
            domain: parts[0].to_string(),
            include_subdomains,
            path: parts[2].to_string(),
            secure,
            expiration,
            name: parts[5].to_string(),
            value: parts[6].to_string(),
        });
    }

    Ok(cookies)
}

pub fn has_bilibili_sessdata(cookies: &[Cookie]) -> bool {
    cookies
        .iter()
        .any(|cookie| cookie.name == "SESSDATA" && !cookie.value.is_empty())
}

/// True for Bilibili-owned domains (`bilibili.com` or any subdomain), guarding
/// against suffix lookalikes like `bilibili.com.evil.com`.
pub fn is_bilibili_domain(domain: &str) -> bool {
    let d = domain.trim_start_matches('.').to_ascii_lowercase();
    d == "bilibili.com" || d.ends_with(".bilibili.com")
}

/// Ensure SESSDATA cookies have a Bilibili domain so Netscape export / yt-dlp work,
/// and drop cookies from other domains (captcha/tracking cookies the login WebView
/// accumulates are not needed for downloads and must not be persisted). Only a
/// domain-less SESSDATA is rewritten onto `.bilibili.com`; a SESSDATA carrying an
/// explicit foreign domain (including suffix lookalikes) is dropped rather than
/// trusted and re-hosted under the Bilibili domain.
pub fn normalize_bilibili_cookies(cookies: &[Cookie]) -> Vec<Cookie> {
    cookies
        .iter()
        .map(|cookie| {
            let mut c = cookie.clone();
            if c.name == "SESSDATA" && c.domain.is_empty() {
                c.domain = ".bilibili.com".into();
                c.include_subdomains = true;
            }
            if c.path.is_empty() {
                c.path = "/".into();
            }
            c
        })
        .filter(|c| is_bilibili_domain(&c.domain))
        .collect()
}

/// Join stored cookies into a `name=value; name=value` request header, keeping only Bilibili domains.
pub fn cookie_header_for_bilibili(cookies: &[Cookie]) -> String {
    cookies
        .iter()
        .filter(|c| is_bilibili_domain(&c.domain) && !c.name.is_empty())
        .map(|c| format!("{}={}", c.name, c.value))
        .collect::<Vec<_>>()
        .join("; ")
}

pub fn write_netscape_file(path: &Path, cookies: &[Cookie]) -> AppResult<()> {
    let mut file = fs::File::create(path)?;
    writeln!(file, "# Netscape HTTP Cookie File")?;
    writeln!(file, "# https://curl.haxx.se/docs/http-cookies.html")?;
    writeln!(
        file,
        "# This file was generated by Video Fetch. Edit at your own risk."
    )?;

    for cookie in cookies {
        writeln!(
            file,
            "{}\t{}\t{}\t{}\t{}\t{}\t{}",
            cookie.domain,
            if cookie.include_subdomains {
                "TRUE"
            } else {
                "FALSE"
            },
            cookie.path,
            if cookie.secure { "TRUE" } else { "FALSE" },
            cookie.expiration,
            cookie.name,
            cookie.value,
        )?;
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = r#"# Netscape HTTP Cookie File
.bilibili.com	TRUE	/	FALSE	0	SESSDATA	abc123
.bilibili.com	TRUE	/	FALSE	0	bili_jct	tok
"#;

    #[test]
    fn parses_sessdata() {
        let cookies = parse_netscape_cookies(SAMPLE).unwrap();
        assert!(has_bilibili_sessdata(&cookies));
        assert_eq!(
            cookies.iter().find(|c| c.name == "SESSDATA").unwrap().value,
            "abc123"
        );
    }

    #[test]
    fn rejects_garbage() {
        assert!(
            parse_netscape_cookies("not a cookies file")
                .unwrap()
                .is_empty()
        );
    }

    fn cookie(domain: &str, name: &str, value: &str) -> Cookie {
        Cookie {
            domain: domain.into(),
            include_subdomains: domain.starts_with('.'),
            path: "/".into(),
            secure: true,
            expiration: 0,
            name: name.into(),
            value: value.into(),
        }
    }

    #[test]
    fn normalize_keeps_only_bilibili_domains() {
        let cookies = vec![
            cookie(".bilibili.com", "SESSDATA", "abc"),
            cookie(".bilibili.com", "bili_jct", "tok"),
            cookie(".geetest.com", "gt", "x"),
            cookie(".doubleclick.net", "id", "y"),
        ];
        let normalized = normalize_bilibili_cookies(&cookies);
        let names: Vec<&str> = normalized.iter().map(|c| c.name.as_str()).collect();
        assert_eq!(names, vec!["SESSDATA", "bili_jct"]);
    }

    #[test]
    fn normalize_rewrites_domainless_sessdata() {
        let cookies = vec![cookie("", "SESSDATA", "abc")];
        let normalized = normalize_bilibili_cookies(&cookies);
        assert_eq!(normalized.len(), 1);
        assert_eq!(normalized[0].domain, ".bilibili.com");
        assert!(normalized[0].include_subdomains);
    }

    #[test]
    fn normalize_drops_sessdata_from_foreign_domain() {
        let cookies = vec![cookie(".example.com", "SESSDATA", "abc")];
        let normalized = normalize_bilibili_cookies(&cookies);
        assert!(normalized.is_empty());
    }

    #[test]
    fn normalize_drops_lookalike_domains() {
        let cookies = vec![
            cookie("bilibili.com.evil.com", "SESSDATA", "abc"),
            cookie("bilibili.com.evil.com", "buvid3", "xyz"),
        ];
        let normalized = normalize_bilibili_cookies(&cookies);
        assert!(normalized.is_empty());
    }

    #[test]
    fn cookie_header_keeps_only_bilibili_domains() {
        let cookies = vec![
            cookie(".bilibili.com", "SESSDATA", "abc"),
            cookie(".bilibili.com", "bili_jct", "tok"),
            cookie(".doubleclick.net", "id", "x"),
        ];
        assert_eq!(
            cookie_header_for_bilibili(&cookies),
            "SESSDATA=abc; bili_jct=tok"
        );
    }

    #[test]
    fn bilibili_domain_matching() {
        assert!(is_bilibili_domain("bilibili.com"));
        assert!(is_bilibili_domain(".bilibili.com"));
        assert!(is_bilibili_domain("www.bilibili.com"));
        assert!(is_bilibili_domain("passport.bilibili.com"));
        assert!(!is_bilibili_domain("bilibili.com.evil.com"));
        assert!(!is_bilibili_domain("notbilibili.com"));
        assert!(!is_bilibili_domain(""));
    }
}
